import "./globals.css";
import type { Metadata } from "next";
import Providers from "./components/providers";
import Navbar from "./components/Navbar";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import GithubSigninBtn from "./components/GithubSigninBtn";
import ThemeButton from "./components/ThemeButton";
import { BsGithub } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          {session ? (
            <>
              <Navbar />
              {children}
            </>
          ) : (
            <div className="font-sans relative h-screen w-full max-h-full flex">
              <div
                className=" w-full bg-primaryBg  flex flex-col items-center
                justify-center"
              >
                <div
                  className="flex flex-col justify-between  items-center border-2 p-4   border-primaryText  
                  shadow-xl w-[420px] min-h-[200px] rounded-3xl"
                >
                  <div className="flex items-center justify-between px-2 w-full">
                    <span className=" text-primaryText font-semibold text-3xl">
                      Welcome
                    </span>
                    <span>
                      <ThemeButton />
                    </span>
                  </div>
                  <GithubSigninBtn />
                </div>
              </div>
            </div>
          )}
        </Providers>
      </body>
    </html>
  );
}
